---
title: "integration"
format: html
editor: visual
---

```{r}
library(Seurat)
library(clustree)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(stringr)

# visualization config
options(bitmapType="cairo")

set.seed(1)

```

```{r}
retina.scrna <- readRDS("../data/retina.preprocessed_ASL1.rds")

retina.scrna@meta.data <- retina.scrna@meta.data |> 
  mutate(
    embryo = str_sub(sample, 1, 2),
    timepoint = case_when(
      grepl("RPE", sample) ~ "0h",
      grepl("6h", sample) ~ "6h",
      grepl("24h", sample) ~ "24h"
    ),
    condition = case_when(
      grepl("FGF", sample) ~ "fgf",
      grepl("RPE", sample) ~ "ref"
    ), condition = if_else(is.na(condition), "rect", condition))
```

```{r}
retina.scrna <- SCTransform(
  retina.scrna, vars.to.regress = c("percent.mt","diff_S_G2M","percent.W"), ncells = 3000, conserve.memory = TRUE, verbose = TRUE)
```

```{r}
retina.scrna <- RunPCA(retina.scrna, features = VariableFeatures(object = retina.scrna))
retina.scrna <- FindNeighbors(retina.scrna, dims=1:15)
retina.scrna <- FindClusters(retina.scrna, resolution = c(0.2))
retina.scrna <- RunUMAP(retina.scrna, dims = 1:15)


DimPlot(retina.scrna, group.by = "condition")
```

```{r}
DimPlot(retina.scrna, group.by = "SCT_snn_res.0.2")
```

```{r}
retina.scrna_sep <- SplitObject(retina.scrna, split.by = "condition")
retina.scrna_sep <- PrepSCTIntegration(retina.scrna_sep, anchor.features = 2000)
anchor_features <- SelectIntegrationFeatures(object.list = retina.scrna_sep)
integration_anchors <- FindIntegrationAnchors(object.list = retina.scrna_sep, normalization.method = "SCT", anchor.features = anchor_features)
retina.scrna.combined <- IntegrateData(anchorset = integration_anchors)
DefaultAssay(retina.scrna.combined) <- "integrated"
```

```{r}
# Run the standard workflow for visualization and clustering
retina.scrna.combined <- ScaleData(retina.scrna.combined, verbose = FALSE)
retina.scrna.combined <- RunPCA(retina.scrna.combined, npcs = 30, verbose = FALSE)
retina.scrna.combined <- RunUMAP(retina.scrna.combined, reduction = "pca", dims = 1:15)
retina.scrna.combined <- FindNeighbors(retina.scrna.combined, reduction = "pca", dims = 1:15)
retina.scrna.combined <- FindClusters(retina.scrna.combined, resolution = c(0.1, 0.12, 0.18, 0.2, 0.11, 0.105, 0.15))
```

```{r}
DimPlot(retina.scrna.combined, group.by = "condition")
```

```{r}
DimPlot(retina.scrna.combined, group.by = "integrated_snn_res.0.105")
```

```{r}
DimPlot(retina.scrna.combined, group.by = "integrated_snn_res.0.2")
```

```{r}
SCT_assay <- GetAssayData(retina.scrna, assay = "SCT", slot = "data")
retina.scrna.combined[["SCT"]] <- CreateAssayObject(data = SCT_assay)
```
```{r}
DefaultAssay(retina.scrna.combined) <- "SCT"
Idents(retina.scrna.combined) <- "integrated_snn_res.0.105"
DimPlot(retina.scrna.combined, group.by = "integrated_snn_res.0.105")
```

## Find markers for cluster 0

```{r}
cluster_i <- "0"

cluster.conserved_markers <- FindConservedMarkers(
  retina.scrna.combined,
  ident.1 = cluster_i,
  assay = "SCT",
  grouping.var = "condition",
  only.pos = TRUE,
  min.pct = 0.25,
  min.diff.pct = 0.25,
  logfc.threshold = 0.25
)

markers_0 <- rownames(cluster.conserved_markers)[1:4]

FeaturePlot(retina.scrna.combined, 
            reduction = "umap", 
            features = markers_0,
            pt.size = 0.4, 
            order = TRUE,
            min.cutoff = 'q10',
            label = TRUE)
```

## Find markers for cluster 1

```{r}
cluster_i <- "1"

cluster.conserved_markers <- FindConservedMarkers(
  retina.scrna.combined,
  ident.1 = cluster_i,
  assay = "SCT",
  grouping.var = "condition",
  only.pos = TRUE,
  min.pct = 0.25,
  min.diff.pct = 0.25,
  logfc.threshold = 0.25
)

markers_1 <- rownames(cluster.conserved_markers)[1:4]

FeaturePlot(retina.scrna.combined, 
            reduction = "umap", 
            features = markers_1,
            pt.size = 0.4, 
            order = TRUE,
            min.cutoff = 'q10',
            label = TRUE)
```

```{r}
## Find markers for cluster 2

cluster_i <- "2"

cluster.conserved_markers <- FindConservedMarkers(
  retina.scrna.combined,
  ident.1 = cluster_i,
  assay = "SCT",
  grouping.var = "condition",
  only.pos = TRUE,
  min.pct = 0.25,
  min.diff.pct = 0.25,
  logfc.threshold = 0.25
)

markers_2 <- rownames(cluster.conserved_markers)[1:4]

FeaturePlot(retina.scrna.combined, 
            reduction = "umap", 
            features = markers_2,
            pt.size = 0.4, 
            order = TRUE,
            min.cutoff = 'q10',
            label = TRUE)

```

## Find markers for cluster 3

```{r}
cluster_i <- "3"

cluster.conserved_markers <- FindConservedMarkers(
  retina.scrna.combined,
  ident.1 = cluster_i,
  assay = "SCT",
  grouping.var = "condition",
  only.pos = TRUE,
  min.pct = 0.25,
  min.diff.pct = 0.25,
  logfc.threshold = 0.25
)

markers_3 <- rownames(cluster.conserved_markers)[1:4]

FeaturePlot(retina.scrna.combined, 
            reduction = "umap", 
            features = markers_3,
            pt.size = 0.4, 
            order = TRUE,
            min.cutoff = 'q10',
            label = TRUE)
```

## Cell type assignment

```{r}
retina.scrna.combined <- RenameIdents(
  object = retina.scrna.combined,
  "0" = "epithelial",
  "1" = "intermediate",
  "2" = "fiber",
  "3" = "intermediate"
)
retina.scrna.combined[["cell_type"]] <- Idents(retina.scrna.combined)

DimPlot(retina.scrna.combined, group.by = "cell_type")
```


```{r}
saveRDS(retina.scrna.combined, "../data/retina.integrated_annotated.ASL1.rds")
```
