---
title: "integration_all"
format: html
editor: visual
---

```{r}
retina.scrna <- readRDS("../data/retina.preprocessed.rds")

retina.scrna@meta.data <- retina.scrna@meta.data |> 
  mutate(
    embryo = str_sub(sample, 1, 2),
    timepoint = case_when(
      grepl("RPE", sample) ~ "0h",
      grepl("6h", sample) ~ "6h",
      grepl("24h", sample) ~ "24h"
    ),
    condition = if_else(grepl("FGF", sample), "sti", "ctl")
  )
```

```{r}
DimPlot(retina.scrna, group.by = "condition")
```

```{r}
DimPlot(retina.scrna, group.by = "SCT_snn_res.0.2")
```

```{r}
retina.scrna_sep <- SplitObject(retina.scrna, split.by = "condition")
retina.scrna_sep <- PrepSCTIntegration(retina.scrna_sep, anchor.features = 2000)
anchor_features <- SelectIntegrationFeatures(object.list = retina.scrna_sep)
integration_anchors <- FindIntegrationAnchors(object.list = retina.scrna_sep, normalization.method = "SCT", anchor.features = anchor_features)
retina.scrna.combined <- IntegrateData(anchorset = integration_anchors)
DefaultAssay(retina.scrna.combined) <- "integrated"
```

```{r}
# Run the standard workflow for visualization and clustering
retina.scrna.combined <- ScaleData(retina.scrna.combined, verbose = FALSE)
retina.scrna.combined <- RunPCA(retina.scrna.combined, npcs = 30, verbose = FALSE)
retina.scrna.combined <- RunUMAP(retina.scrna.combined, reduction = "pca", dims = 1:15)
retina.scrna.combined <- FindNeighbors(retina.scrna.combined, reduction = "pca", dims = 1:15)
retina.scrna.combined <- FindClusters(retina.scrna.combined, resolution = 0.2)
```

```{r}
DimPlot(retina.scrna.combined, group.by = "condition")
```

```{r}
DimPlot(retina.scrna.combined, group.by = "integrated_snn_res.0.2")
```

```{r}
saveRDS(retina.scrna.combined, "../data/retina.integrated.all.rds")
```
