```{r}
library(RCurl)
library(tidyverse)
library(Seurat)
```


```{r}
#create directories
working_dir <- getwd()

raw_data_dir <- working_dir |>
  substr(1, nchar(working_dir)-2) |>
  paste("_raw", sep = "/")

data_dir <- working_dir |>
  substr(1, nchar(working_dir)-2) |>
  paste("data", sep = "/")

dir.create(file.path(raw_data_dir))
dir.create(file.path(data_dir))
```


```{r}
#get filenames
#https://ftp.ncbi.nlm.nih.gov/geo/series/GSE236nnn/GSE236902/suppl/GSE236902%5FDGE.mtx.gz
url = "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE236nnn/GSE236902/suppl/"
filenames <- getURL(url, ftp.use.epsv = FALSE, dirlistonly = TRUE)
filenames <- strsplit(filenames, "\\n")
filenames <- unlist(filenames)
filenames
```
```{r}
#download files
for (filename in filenames) {
  download.file(paste(url, filename, sep = ""), paste(raw_data_dir, "/", filename, sep = ""))
}
```


```{r}
#create seurat object
matrix_file <- paste(raw_data_dir, "GSE236902_DGE.mtx.gz", sep = "/")
features_file <- paste(raw_data_dir, "GSE236902_all_genes.csv.gz", sep = "/")
cell_file <- paste(raw_data_dir, "GSE236902_cell_metadata.csv.gz", sep = "/")


cell_object <- read_csv(cell_file)
features_object <- read_csv(features_file)
matrix_object <- Matrix::readMM(matrix_file)
```


```{r}
# create expression matrix from files
expression_matrix <- ReadMtx(
  mtx = matrix_file, 
  features = features_file,
  cells = cell_file,
  cell.sep = ",",
  feature.sep = ",",
  mtx.transpose = T,
  unique.features = T,
  skip.cell = 1,
  skip.feature = 1
)


#removing unidentified genes
to_remove <- which(rownames(expression_matrix) == "")
expression_matrix <- expression_matrix[-grep("^\\.", row.names(expression_matrix)),]
expression_matrix <- expression_matrix[-which(rownames(expression_matrix) == ""),]


#create seurat object
seurat_object <- CreateSeuratObject(counts = expression_matrix, meta.data = cell_object)

#save seurat object 
saveRDS(seurat_object, paste(data_dir, "retina.rds", sep = "/"))
```



