```{r}
library(RCurl)
library(tidyverse)
library(Seurat)
library(hdf5r)
```


```{r}
#create directories
working_dir <- getwd()

raw_data_dir <- working_dir |>
  substr(1, nchar(working_dir)-2) |>
  paste("_raw", sep = "/")

data_dir <- working_dir |>
  substr(1, nchar(working_dir)-2) |>
  paste("data", sep = "/")

dir.create(file.path(raw_data_dir))
dir.create(file.path(data_dir))
```
```{r}
#get filenames (metadata and genes)

url = "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE236nnn/GSE236902/suppl/"
filenames <- getURL(url, ftp.use.epsv = FALSE, dirlistonly = TRUE)
filenames <- strsplit(filenames, "\\n")
filenames <- unlist(filenames)
filenames

```


```{r}
#get filenames 2 (count matrix)

url2 = "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE236nnn/GSE236903/suppl/"
filenames2 <- getURL(url2, ftp.use.epsv = FALSE, dirlistonly = TRUE)
filenames2 <- strsplit(filenames2, "\\n")
filenames2 <- unlist(filenames2)
filenames2

#https://ftp.ncbi.nlm.nih.gov/geo/series/GSE236nnn/GSE236903/suppl/GSE236903%5Ffiltered%5Ffeature%5Fbc%5Fmatrix.h5
```
```{r}
#download files
for (filename in filenames) {
  download.file(paste(url, filename, sep = ""), paste(raw_data_dir, "/", filename, sep = ""))
}

for (filename in filenames2) {
  download.file(paste(url2, filename, sep = ""), paste(raw_data_dir, "/", filename, sep = ""))
}
```


```{r}
#count matrix file name
hdf5_file <- paste(raw_data_dir, "GSE236903_filtered_feature_bc_matrix.h5", sep = "/")
features_file <- paste(raw_data_dir, "GSE236902_all_genes.csv.gz", sep = "/")
cell_file <- paste(raw_data_dir, "GSE236902_cell_metadata.csv.gz", sep = "/")
```


```{r}
#
count_matrix <- Read10X_h5(hdf5_file, use.names = TRUE, unique.features = TRUE)
cell_object <- read_csv(cell_file)
features_object <- read_csv(features_file)


seurat_object <- CreateSeuratObject(counts = count_matrix, meta.data = cell_object)

saveRDS(seurat_object, paste(data_dir, "retina_2.rds", sep = "/"))
```


```{r}
#
seurat_file <- paste(data_dir, "retina_2.rds", sep = "/")
retina <- readRDS(seurat_file)


retina@meta.data |>
  ggplot(aes(x = "X",y = nCount_RNA)) + geom_violin() + geom_point(alpha = 0.1, position=position_jitter(height=.5, width=.5))

retina@meta.data |>
  ggplot(aes(x = "X",y = nFeature_RNA)) + geom_violin() + geom_point(alpha = 0.1, position=position_jitter(height=.5, width=.5))
```